import { inter } from './fonts'
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-[#1D1E22]'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
